[package]
name = "new-pro"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "~1.9.9"
getrandom = { version = "0.2.2", features = ["custom"] }

[lib]
crate-type = ["cdylib", "lib"]
