[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
fantasy = "GtyvgHNxNFrbSf4AJSiwsJjUqvmE7vLCykfoV7oRPicV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/smitty/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
